### ISSUE TITLE
application没有代码

### ISSUE THREAD

**Issue by Raidohub** [smingjie/bbq-ddd#4]
按理说api层调用application，application调用domain层。
而当前代码是api调用domain，applicaion反而没有代码，很好奇

**Comment by smingjie** [comment]
因为没有涉及到跨领域协作的功能，所以这里不一定要写哈。假设在CQRS模式下（1）如果涉及到跨领域的查询如分页查询有管理员角色的用户信息详情，这种要跨用户user域和rbac域去查询，这种会写在application，这种可以直接从application层跨过domain层去查Infrastructure层（2）如果是跨领域的更新如创建一个工作流实例，可从应用层application协调（查询流程配置，根据流程配置部署实例，根据实例初始化情况发出通知到指定人）涉及到流程域和通知域的协作。
